USE [master]
GO

/****** Object:  Login [SQL2012-1\Lance]    Script Date: 12/19/2017 12:00:25 AM ******/
CREATE LOGIN [SQL2012-1\Lance] FROM WINDOWS WITH DEFAULT_DATABASE=[GreenGrocerDB], DEFAULT_LANGUAGE=[us_english]
GO

ALTER SERVER ROLE [sysadmin] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [securityadmin] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [serveradmin] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [setupadmin] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [processadmin] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [diskadmin] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [dbcreator] ADD MEMBER [SQL2012-1\Lance]
GO

ALTER SERVER ROLE [bulkadmin] ADD MEMBER [SQL2012-1\Lance]
GO

USE [GreenGrocerDB]
GO
CREATE USER [SQL2012-1\Lance] FOR LOGIN [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_accessadmin] ADD MEMBER [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_backupoperator] ADD MEMBER [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_datareader] ADD MEMBER [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_ddladmin] ADD MEMBER [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_owner] ADD MEMBER [SQL2012-1\Lance]
GO
USE [GreenGrocerDB]
GO
ALTER ROLE [db_securityadmin] ADD MEMBER [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ADMINISTER BULK OPERATIONS TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY AVAILABILITY GROUP TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY CONNECTION TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY CREDENTIAL TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY DATABASE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY ENDPOINT TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY EVENT NOTIFICATION TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY EVENT SESSION TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY LOGIN TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY SERVER AUDIT TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER ANY SERVER ROLE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER RESOURCES TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER SERVER STATE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER SETTINGS TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT ALTER TRACE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT AUTHENTICATE SERVER TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CONNECT SQL TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CONTROL SERVER TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CREATE ANY DATABASE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CREATE AVAILABILITY GROUP TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CREATE DDL EVENT NOTIFICATION TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CREATE ENDPOINT TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CREATE SERVER ROLE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT CREATE TRACE EVENT NOTIFICATION TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT EXTERNAL ACCESS ASSEMBLY TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT SHUTDOWN TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT UNSAFE ASSEMBLY TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT VIEW ANY DATABASE TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT VIEW ANY DEFINITION TO [SQL2012-1\Lance]
GO
use [master]
GO
GRANT VIEW SERVER STATE TO [SQL2012-1\Lance]
GO


