USE [master]
GO

/****** Object:  Database [GreenGrocerDB]    Script Date: 12/17/2017 4:39:12 PM ******/
CREATE DATABASE [GreenGrocerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GreenGrocerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GreenGrocerDB.mdf' , SIZE = 102400KB , MAXSIZE = 204800KB , FILEGROWTH = 5%), 
 FILEGROUP [DATA]  DEFAULT 
( NAME = N'GreenGrocerData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GreenGrocerData.ndf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GreenGrocerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\GreenGrocerDB_log.ldf' , SIZE = 51200KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [GreenGrocerDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GreenGrocerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GreenGrocerDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [GreenGrocerDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GreenGrocerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GreenGrocerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GreenGrocerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GreenGrocerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET RECOVERY FULL 
GO

ALTER DATABASE [GreenGrocerDB] SET  MULTI_USER 
GO

ALTER DATABASE [GreenGrocerDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GreenGrocerDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GreenGrocerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GreenGrocerDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [GreenGrocerDB] SET  READ_WRITE 
GO

